
networks:
  db:
    internal: true
    enable_ipv6: false
  api:

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=group_n_meet
    ports:
      - "0.0.0.0:5432:5432"
    user: postgres
    volumes:
      - ./postgresql/.postgres-data:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    expose:
      - 8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=group_n_meet
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
    depends_on:
      - postgres
    networks:
      - db
      - api
