[package]
name = "group_n_meet_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.43", features = ["serde"] }
log = "0.4.29"
postgres = "0.19.12"
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
sqlx = { version = "0.8.6", features = ["chrono", "derive", "json", "postgres", "uuid"] }
uuid = { version = "1.19.0", features = ["serde", "v7"] }
