FROM python:3.11-alpine


WORKDIR /app
COPY . /app

## Installing build dependencies
RUN apk update && \
    apk add --no-cache build-base gcc musl-dev

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
CMD ["uvicorn", "main:app"]
