FROM rust:alpine AS builder

RUN apk add --no-cache musl-dev pkgconfig openssl-dev ca-certificates git
WORKDIR /app
COPY . .
RUN cargo build --release

FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/target/release/backend .
EXPOSE 8080
CMD ["./backend"]
